### ISSUE TITLE
Failed to parse request

### ISSUE THREAD

**Issue by hoest** [WiebeCnossen/gnarl#1]
Error while running `gnarl shrink`:

```
2021/06/08 10:58:05 failed to parse request 0.28.0 - 0.30.0: invalid term 0.28.0 - 0.30.0: invalid major -: strconv.ParseInt: parsing "-": invalid syntax
```

I've added my `yarn.lock` file as ZIP.

Example:

```
"@material-ui/icons@npm:^3.0.2":
  version: 3.0.2
  resolution: "@material-ui/icons@npm:3.0.2"
  dependencies:
    "@babel/runtime": ^7.2.0
    recompose: 0.28.0 - 0.30.0
  peerDependencies:
    "@material-ui/core": ^3.0.0
    react: ^16.3.0
    react-dom: ^16.3.0
  checksum: fb0965ac09581d835f562a44616e2943a42865e1ed8daab2b952f7db25524963b7d6b7b06fe2d05aa7041fe7fb2a741867737e08a717312d5d416613dc7eaee0
  languageName: node
  linkType: hard
```

[yarn.lock.zip](https://github.com/WiebeCnossen/gnarl/files/6615039/yarn.lock.zip)
